version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_KIBANA_VERSIONING: $ELASTIC_KIBANA_VERSIONING
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elasticNet

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_KIBANA_VERSIONING: $ELASTIC_KIBANA_VERSIONING
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elasticNet
    depends_on:
      - elasticsearch

networks:
  elasticNet:
    driver: bridge
